# -*- coding: utf-8 -*-
"""Project 4 - COVID case Data Analysis_04022026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ucExXhcgUtUnu3iw47Fpf167JMjhLS4y

Agenda

1. Daily vs Cumulative Cases
2. Top Affected Countries
3. Death Rate Calculation
4. Trend Analysis with Line Plots
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/covid19_dataset.csv')
df.head()

df['Date'].dtype

# Convert Date column
df['Date'] = pd.to_datetime(df['Date'])

# Daily Confirmed Cases

df[['Date','Country','Confirmed_Cases']].head()

# Cumulative Case by Country

df['Cumulative_Cases'] = df.groupby('Country')['Confirmed_Cases'].cumsum()
df['Cumulative_Cases']
df.head()

# Top Affected Country (Total Cases)

top_countries = (
    df.groupby('Country')['Confirmed_Cases']
    .sum()
    .sort_values(ascending=False)
    .head(10)
)
print(top_countries)

# Chart for Top Affected Country (Total Cases)

import matplotlib.pyplot as plt

top_countries.plot(kind = 'bar')
plt.title('Top 10 Countries by Total Confirmed Cases')
plt.xlabel('Country')
plt.ylabel('Total Cases')
plt.show()

# Death Rate Calculation

# Formula : Death Rate (%) = Total Death / Total Confirmed Cases x 100

summary = df.groupby('Country')[['Confirmed_Cases', 'Deaths']].sum()
summary['Death_Rate (%)'] = (summary['Deaths'] / summary['Confirmed_Cases']) * 100
summary.sort_values('Death_Rate (%)' , ascending= False ).head(10)

# Trend Analysis with Line Plots

country = 'Germany'
country_df = df[df['Country'] == country]

plt.plot(country_df['Date'],country_df['Cumulative_Cases'])
plt.title('Cumulative Cases Over Time')
plt.xlabel('Date')
plt.ylabel('Cumulative Cases')
plt.show()

# Compare Countries

countries = ['Germany','UK','France']

for c in countries:
  temp = df[df['Country'] == c]
  plt.plot(temp['Date'],temp['Cumulative_Cases'],label = c)

  plt.legend()
  plt.title('COVID-19 Cases Trends by Country')
  plt.xlabel('Date')
  plt.ylabel('Cumulative Cases')
  plt.show()