# -*- coding: utf-8 -*-
"""Project 2 - Pandas Weather Insight_07122025 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G5OrD2s5tSV36KqWzsjVBkCZEUbCA5Um
"""

import requests

API_KEY = "zpka_dba6f0c502ba4f8f9007c387579d0625_e2ae07cc"

def city_search(api_key, q):
  end_point = "http://dataservice.accuweather.com/locations/v1/cities/search"
  params = {
      'apikey': api_key,
      'q': q
  }
  response = requests.get(end_point, params=params)

  if response.status_code == 200:
    return response.json()
  else:
    print(f'Error: {response.status_code}')
    return None

city_result1 = city_search(API_KEY, 'Kuala Lumpur')
print(city_result1)

for x in city_result1:
  print (x)

city_result2 = city_search(API_KEY, 'Singapore')
print(city_result2)

for x in city_result2:
  print (x)

def get_current_conditions(api_key, location_key):
  endpoint = f'http://dataservice.accuweather.com/currentconditions/v1/{location_key}'
  params = {
      'apikey': api_key,
  }
  response = requests.get(endpoint, params=params)
  if response.status_code == 200:
    return response.json()
  else:
    print(f'Error: {response.status_code}')
    return None

print(city_result1[0])
kl_key = city_result1[0]['Key']
print(kl_key)

cond1 = get_current_conditions(API_KEY, kl_key)
print(cond1)

# To get daily forecast

def get_daily_forecast(api_key, location_key):
  endpoint = f'http://dataservice.accuweather.com/forecasts/v1/daily/1day/{location_key}'
  params = {
      'apikey': api_key,
      'metric': True
  }
  response = requests.get(endpoint, params=params)
  if response.status_code == 200:
    return response.json()
  else:
    print(f'Error: {response.status_code}')
    return None

print(city_result1[0])
kl_key = city_result1[0]['Key']
print(kl_key)

forecast = get_daily_forecast(API_KEY, kl_key)
print(forecast)

def fahrenheit_to_celsius(fahrenheit):
  celsius = (fahrenheit - 32) * 5/9
  return celsius

from datetime import datetime
def fetch_weather_data(api_key, name):
  city_infos = city_search(api_key, name)
  city_info = city_infos[0]
  city_name = city_info['LocalizedName']
  city_key = city_info['Key']
  country_name = city_info['Country']['LocalizedName']
  current_conditions = get_current_conditions(api_key, city_key)
  current_condition = current_conditions[0]
  observation_time = current_condition['LocalObservationDateTime']
  formatted_time = datetime.strptime(observation_time, "%Y-%m-%dT%H:%M:%S%z").strftime('%Y-%m-%d %H:%M:%S %Z')
  temperature = current_condition['Temperature']['Metric']['Value']
  weather_text = current_condition['WeatherText']
  is_day_time = current_condition['IsDayTime']

  daily_forecast = get_daily_forecast(api_key, city_key)

  min_temp_f = daily_forecast['DailyForecasts'][0]['Temperature']['Minimum']['Value']
  min_temp_c = fahrenheit_to_celsius(min_temp_f)
  max_temp_f = daily_forecast['DailyForecasts'][0]['Temperature']['Maximum']['Value']
  max_temp_c = fahrenheit_to_celsius(max_temp_f)
  forecast_text = daily_forecast["DailyForecasts"][0]["Day"]["IconPhrase"]

  data = {  # create dictionary for the data we get from forecast
      'City' : city_name,
      'Country' : country_name,
      'Temperature (C)' : temperature,
      'Weather Text' : weather_text,
      'Local Observation Time' : formatted_time,
      'DayTime' : is_day_time,
      'Forecast Min Temp (C)' : round(min_temp_c,1),
      'Forecast Max Temp (C)' : round(max_temp_c,1),
      'Forecast Text' : forecast_text
  }
  return data

data = fetch_weather_data(API_KEY, 'Kuala Lumpur')
print(data)

for x in data :
  print(x, ':', data[x])

from IPython.display import display
import pandas as pd
weather_list = []

while True:
  user_input = input('Enter the name of the city (or type -exit- to finish) :')
  if user_input.lower().strip() == 'exit':
    break
  else:
    try:
      weather_data = fetch_weather_data(API_KEY, user_input)
      weather_list.append(weather_data)
    except IndexError:
      print('No such city as', user_input)
    except TypeError:
      print('Cannot input empty data')

print("--" * 150)
df = pd.DataFrame(weather_list)
print('')
display(df)

print('\nData Analysis: ')
print(f"Average Temperature (C): {round(df['Temperature (C)'].mean())}")
print(f"Unique Weather Description: {df['Weather Text'].unique()}")